---
networks:
  my-bridge:

services:
  worker1:
    build:
      context: ../worker
      dockerfile: ./Dockerfile
    image: worker1
    networks:
      - my-bridge
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully

  worker2:
    build:
      context: ../worker
      dockerfile: ./Dockerfile
    image: worker1
    networks:
      - my-bridge
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully

  worker3:
    build:
      context: ../worker
      dockerfile: ./Dockerfile
    image: worker1
    networks:
      - my-bridge
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully

  manager:
    build:
      context: ../manager
      dockerfile: ./Dockerfile
    image: manager
    ports:
      - "${MANAGER_PORTS}"
    networks:
      - my-bridge
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - "./rabbitmq.env"
    volumes:
      - ./rabbitmq:/tmp/rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q check_port_connectivity && rabbitmq-diagnostics -q cluster_status && rabbitmq-diagnostics -q check_local_alarms" ]
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-bridge

  mongodb1:
    image: mongo
    networks:
      - my-bridge
    volumes:
      - ./data1:/data/db
      - ./mongodb_config:/data/configdb
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({serverStatus:1}).ok' | mongosh MD5HashCrack --quiet | grep 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--config", "/data/configdb/mongod.conf"]

  mongodb2:
    image: mongo
    networks:
      - my-bridge
    volumes:
      - ./data2:/data/db
      - ./mongodb_config:/data/configdb
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({serverStatus:1}).ok' | mongosh MD5HashCrack --quiet | grep 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 27018:27017
    entrypoint: [ "/usr/bin/mongod", "--config", "/data/configdb/mongod.conf"]

  mongodb3:
    image: mongo
    networks:
      - my-bridge
    volumes:
      - ./data3:/data/db
      - ./mongodb_config:/data/configdb
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({serverStatus:1}).ok' | mongosh MD5HashCrack --quiet | grep 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 27019:27017
    entrypoint: [ "/usr/bin/mongod", "--config", "/data/configdb/mongod.conf"]

  mongo-init:
    image: mongo
    networks:
      - my-bridge
    depends_on:
      mongodb1:
        condition: service_healthy
      mongodb2:
        condition: service_healthy
      mongodb3:
        condition: service_healthy
    volumes:
      - ./deployment_scripts/initiate_replica.sh:/deployment_scripts/initiate_replica.sh:ro
    entrypoint: ["bash", "/deployment_scripts/initiate_replica.sh"]

  mongo-express:
    image: mongo-express
    ports:
      - "8089:8081"
    environment:
    - ME_CONFIG_MONGODB_URL=mongodb://mongodb1:27017,mongodb2:27017,mongodb3:27017/?replicaSet=rs0
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    networks:
      - my-bridge

volumes:
  data1:
  data2:
  data3:
  mongodb_config:
  rabbitmq:
