---
networks:
  my-bridge:

services:
  worker1:
    build:
      context: ../worker
      dockerfile: ./Dockerfile
    image: worker1
    env_file: "./work.env"
    networks:
      - my-bridge

  worker2:
    build:
      context: ../worker
      dockerfile: ./Dockerfile
    image: worker1
    env_file: "./work.env"
    networks:
      - my-bridge

  worker3:
    build:
      context: ../worker
      dockerfile: ./Dockerfile
    image: worker1
    env_file: "./work.env"
    networks:
      - my-bridge


  manager:
    build:
      context: ../manager
      dockerfile: ./Dockerfile
    image: manager
    env_file: 
     - "./manag.env"
    ports:
      - "${MANAGER_PORTS}"
    networks:
      - my-bridge
